CREATE DATABASE EGGSDB;

CREATE TABLE EGGSDB.dbo.[USER](
ID			BIGINT			NOT NULL IDENTITY(1,1),
Email		VARCHAR(345)	NOT NULL,
[Password]	VARCHAR(128)	NOT NULL,
FirstName	CHAR(30)		NULL,
LastName	CHAR(30)		NULL,
CONSTRAINT	USER_PK			PRIMARY KEY NONCLUSTERED(ID),
CONSTRAINT	UIX_USER_EMAIL	UNIQUE CLUSTERED(Email)
);

CREATE TABLE EGGSDB.dbo.[IP](
Email		VARCHAR(345)	UNIQUE	NOT NULL,
IPv4		CHAR(15)		NULL,
IPv6		CHAR(39)		NULL,
CONSTRAINT	IP_PK			PRIMARY KEY(Email),
CONSTRAINT	IP_FK			FOREIGN KEY(Email)
REFERENCES EGGSDB.dbo.[USER](Email)
ON UPDATE CASCADE
ON DELETE CASCADE
);

CREATE TABLE EGGSDB.dbo.REQUEST(
Email		VARCHAR(345)	UNIQUE	NOT NULL,
Requests	BIGINT			NOT NULL DEFAULT 0,
[Status]	BIT				NULL	DEFAULT 0,
CONSTRAINT	REQUEST_PK		PRIMARY KEY(Email),
CONSTRAINT	REQUEST_FK		FOREIGN KEY(Email)
REFERENCES EGGSDB.dbo.[USER](Email)
ON UPDATE CASCADE
ON DELETE CASCADE
);

CREATE TABLE EGGSDB.dbo.DIRECTORY(
ID		BIGINT			NOT NULL IDENTITY(1,1),
Email	VARCHAR(345)	NOT NULL,

);